defaults:
- main
- _self_

src_dir: data/interim
pca: true
tsne: false
abs: true
ref: false
box_extension: {Ablation: [0, 0]}   # class: (horizontal, vertical)
train_size: 0.80
seed: 11
save_dir: data/coco
